sudo: required

language: bash

services:
  - docker

install:
  - docker build -t intelliops/cronicle:latest -f Dockerfile .
  - docker build -t intelliops/cronicle-letsencrypt:latest -f Dockerfile.letsencrypt .
  - docker run --name cronicle -d -p 127.0.0.1:3012:3012 intelliops/cronicle:latest
  - docker run --name cronicle-letsencrypt -d -p 127.0.0.1:4012:3012 intelliops/cronicle-letsencrypt:latest

script:
  - docker ps -a
  - sleep 20
  - docker exec cronicle /bin/ash -c "cat /opt/cronicle/conf/config.json"
  - docker exec cronicle-letsencrypt /bin/ash -c "cat /opt/cronicle/conf/config.json"
  - curl http://localhost:3012 | grep LICENSE
  - curl http://localhost:4012 | grep LICENSE
  - docker stop cronicle cronicle-letsencrypt
  - docker rm -f cronicle cronicle-letsencrypt

deploy:
  provider: script
  script: release.sh
  on:
    branch: master
